select * from customer limit 20;

--Q1.What is the total revenue generated by male vs.female customer?
SELECT "Customer ID", "Purchase Amount (USD)"
FROM customer
WHERE "Discount Applied" = 'Yes'
  AND "Purchase Amount (USD)" >= (
      SELECT AVG("Purchase Amount (USD)") FROM customer
  );
--Q2.Which customers used a discount but still spend more than the average purchase amount?
SELECT "Customer ID", "Purchase Amount (USD)"
FROM customer
WHERE "Discount Applied" = 'Yes'
  AND "Purchase Amount (USD)" >= (
      SELECT AVG("Purchase Amount (USD)") 
      FROM customer
  );
--Q3.Which are the top 5 products with the highest average review rating?
SELECT 
    "Item Purchased",
    ROUND(AVG("Review Rating"::numeric), 2) AS "Average Rating"
FROM customer
GROUP BY "Item Purchased"
ORDER BY "Average Rating" DESC
LIMIT 5;
--Q4.Compare the average purchase amounts between  standard and express shipping
SELECT 
    "Shipping Type",
    ROUND(AVG("Purchase Amount (USD)"::numeric), 2) AS "Average Purchase Amount"
FROM customer
WHERE "Shipping Type" IN ('Standard', 'Express')
GROUP BY "Shipping Type";
--Q5.Do subscribed customers spending more? compare average speed and total revenue
--between subscribers and non subscribes
SELECT 
    "Subscription Status",
    COUNT("Customer ID") AS "Total Customers",
    ROUND(AVG("Purchase Amount (USD)"::numeric), 2) AS "Average Spending",
    SUM("Purchase Amount (USD)"::numeric) AS "Total Revenue"
FROM customer
GROUP BY "Subscription Status"
ORDER BY 
    CASE 
        WHEN "Subscription Status" = 'Yes' THEN 1
        WHEN "Subscription Status" = 'No' THEN 2
    END;
--Q6.Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    "Item Purchased",
    ROUND(
        100.0 * SUM(CASE WHEN "Discount Applied" = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),
        2
    ) AS "Discount Percentage"
FROM customer
GROUP BY "Item Purchased"
ORDER BY "Discount Percentage" DESC
LIMIT 5;
--Q7.Segment customers into New, returning, and loyal based on their total 
--number of previous purchases, and show the count of each segment?

WITH customer_type AS (
  SELECT 
    "Customer ID",
    "Previous Purchases",
    CASE
      WHEN "Previous Purchases" = 1 THEN 'New'
      WHEN "Previous Purchases" BETWEEN 2 AND 10 THEN 'Returning'
      ELSE 'Loyal'
    END AS customer_segment
  FROM customer
)
SELECT 
  customer_segment AS "Customer Segment",
  COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment
ORDER BY 
  CASE 
    WHEN customer_segment = 'Returning' THEN 1
    WHEN customer_segment = 'New' THEN 2
    WHEN customer_segment = 'Loyal' THEN 3
  END;
--Q8.What are the top 3 most purchased products within each category?
-- Q8. What are the top 3 most purchased products within each category?

WITH product_counts AS (
  SELECT 
    "Category",
    "Item Purchased",
    COUNT(*) AS total_purchases
  FROM customer
  GROUP BY "Category", "Item Purchased"
),
ranked AS (
  SELECT 
    "Category",
    "Item Purchased",
    total_purchases,
    ROW_NUMBER() OVER (
      PARTITION BY "Category"
      ORDER BY total_purchases DESC
    ) AS rank
  FROM product_counts
)
SELECT 
  "Category",
  "Item Purchased",
  total_purchases AS "Total Purchases"
FROM ranked
WHERE rank <= 3
ORDER BY "Category", "Total Purchases" DESC;

--Q9.Are cutomers who are repeat buyers (more than 5 previous purchases) also likely
--to subscribe
SELECT 
  'Repeat Buyer' AS "Customer Type",
  "Subscription Status",
  COUNT(*) AS "Number of Customers"
FROM customer
WHERE "Previous Purchases" > 5
GROUP BY "Subscription Status"
ORDER BY "Subscription Status" DESC;
--Q10.What is the revenue contribution of each age group?
SELECT
    CASE
        WHEN "Age" BETWEEN 18 AND 25 THEN 'Young Age'
        WHEN "Age" BETWEEN 26 AND 40 THEN 'Middle Age'
        WHEN "Age" BETWEEN 41 AND 60 THEN 'Adult'
        ELSE 'Senior'
    END AS age_group,
    SUM("Purchase Amount (USD)") AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;









